package enums;

public enum TappeTram {

	STAZIONE_TERMINI,
	COLLI_PORTUENSI,
	SAN_GIOVANNI,
	GIANICOLENSE,
	SAN_CAMILLO,
	PONTE_BIANCO,
	STAZIONE_TRASTEVERE,
	MINISTERO_PUBBLICA_ISTRUZIONE,
	STAZIONE_TIBURTINA
}